CREATE TABLE IF NOT EXISTS `utilizador` (
  `U_ID` int(11) NOT NULL AUTO_INCREMENT,
  `U_NOME` varchar(40) NOT NULL,
  `U_EMAIL` varchar(40) NOT NULL,
  `U_PASSWORD` varchar(255) NOT NULL,
  `U_FOTOGRAFIA` varchar(100) DEFAULT '/Nextour/pasta_fotografias_perfil/default.jpg',
  PRIMARY KEY (`U_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `local` (
  `LO_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `LO_MORADA` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `LO_DISTRITO` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `LO_LONGITUDE` decimal(11,8) DEFAULT NULL,
  `LO_LATITUDE` decimal(11,8) DEFAULT NULL,
  PRIMARY KEY (`LO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `guiaturistico` (
  `GT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `U_ID` int(11) DEFAULT NULL,
  `LO_ID` bigint(20) DEFAULT NULL,
  `GT_NOME` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `GT_DESCRICAO` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `GT_AUDIO` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `GT_DURACAO` int(11) DEFAULT NULL,
  PRIMARY KEY (`GT_ID`),
  KEY `FK_GUIATURISTICO_LOCAL` (`LO_ID`),
  KEY `FK_GUIATURISTICO_UTILIZADOR` (`U_ID`),
  CONSTRAINT `FK_GUIATURISTICO_LOCAL` FOREIGN KEY (`LO_ID`) REFERENCES `local` (`LO_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_GUIATURISTICO_UTILIZADOR` FOREIGN KEY (`U_ID`) REFERENCES `utilizador` (`U_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `pontoparagem` (
  `PP_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `LO_ID` bigint(20) DEFAULT NULL,
  `GT_ID` bigint(20) DEFAULT NULL,
  `PP_NOME` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `PP_AUDIO` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `PP_DESCRICAO` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`PP_ID`),
  KEY `FK_GUIATURISTICO_PONTOPARAGEM` (`GT_ID`),
  KEY `FK_PONTOPARAGEM_LOCAL` (`LO_ID`),
  CONSTRAINT `FK_GUIATURISTICO_PONTOPARAGEM` FOREIGN KEY (`GT_ID`) REFERENCES `guiaturistico` (`GT_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_PONTOPARAGEM_LOCAL` FOREIGN KEY (`LO_ID`) REFERENCES `local` (`LO_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `classificacao` (
  `CA_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `GT_ID` bigint(20) DEFAULT NULL,
  `U_ID` int(11) DEFAULT NULL,
  `CA_VALOR` int(11) DEFAULT NULL,
  PRIMARY KEY (`CA_ID`),
  KEY `FK_GUIATURISTICO_CLASSIFICACAO` (`GT_ID`),
  KEY `FK_UTILIZADOR_CLASSIFICACAO` (`U_ID`),
  CONSTRAINT `FK_GUIATURISTICO_CLASSIFICACAO` FOREIGN KEY (`GT_ID`) REFERENCES `guiaturistico` (`GT_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_UTILIZADOR_CLASSIFICACAO` FOREIGN KEY (`U_ID`) REFERENCES `utilizador` (`U_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE IF NOT EXISTS `favorito` (
  `FA_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `U_ID` int(11) DEFAULT NULL,
  `GT_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`FA_ID`),
  KEY `FK_FAVORITO_UTILIZADOR` (`U_ID`),
  KEY `FK_FAVORITO_GUIATURISTICO` (`GT_ID`),
  CONSTRAINT `FK_FAVORITO_GUIATURISTICO` FOREIGN KEY (`GT_ID`) REFERENCES `guiaturistico` (`GT_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_FAVORITO_UTILIZADOR` FOREIGN KEY (`U_ID`) REFERENCES `utilizador` (`U_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `imagem` (
  `IM_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `GT_ID` bigint(20) DEFAULT NULL,
  `PP_ID` bigint(20) DEFAULT NULL,
  `IM_URL` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`IM_ID`),
  KEY `FK_GUIATURISTICO_IMAGEM` (`GT_ID`),
  KEY `FK_PONTOPARAGEM_IMAGEM` (`PP_ID`),
  CONSTRAINT `FK_GUIATURISTICO_IMAGEM` FOREIGN KEY (`GT_ID`) REFERENCES `guiaturistico` (`GT_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_PONTOPARAGEM_IMAGEM` FOREIGN KEY (`PP_ID`) REFERENCES `pontoparagem` (`PP_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;